### ISSUE TITLE
doubt for c++ api

### ISSUE THREAD

**Issue by Tveek** [luoyetx/mx-lsoftmax#12]
following code,where your definition of those two parameter(data,label) in lsoftmax-inl.h,how python know those params
`fc4 = mx.sym.LSoftmax(data=embedding, label=label, num_hidden=10,
                                  beta=args.beta, margin=args.margin, scale=args.scale,
                                  beta_min=args.beta_min, verbose=True)`

**Comment by luoyetx** [comment]
It's handled by mxnet python package

**Comment by Tveek** [comment]
can be more detailed? which file?thanks!

**Comment by luoyetx** [comment]
It's complex to explain the parameter parsing and how mxnet treat the operator parameters and input symbols. `data` and `label` is the input symbol for LSoftmax operator, as well as `weight` which is not specific written in the code and mxnet also will handle this automatically. Please read the python and c++ code to understand the underline mechanism.
