### ISSUE TITLE
Why minus -w[yi] in `x_grad[i] += alpha * o_grad[i, yi] * (df_dx - w[yi])`?

### ISSUE THREAD

**Issue by yxchng** [luoyetx/mx-lsoftmax#17]
Do you mind explaining this part? I am unable to get why need to -w[yi] here.

**Comment by luoyetx** [comment]
see [here](https://luoyetx.github.io/2017/05/derivatives-for-lsoftmax/).

**Comment by yxchng** [comment]
![screenshot from 2018-04-27 10-19-47](https://user-images.githubusercontent.com/10518587/39341183-8efb4822-4a04-11e8-816e-96ac2bdb6aa9.png)

这里还是不理解： 这两行开起来是一样的啊，怎么后面就多出了个 -w[yi]?

**Comment by luoyetx** [comment]
求和的下标不一样

**Comment by luoyetx** [comment]
这样做是为了方便计算第一项，也就是原始全连接的梯度

**Comment by yxchng** [comment]
懂了谢谢
