### ISSUE TITLE
How to run c++ code?

### ISSUE THREAD

**Issue by Sleepychord** [luoyetx/mx-lsoftmax#7]
Hi, I am a freshman about mxnet and wonder to know how to run your code(c++ version). Could you help me, please?

**Comment by luoyetx** [comment]
copy cpp code under `operator`  folder to mxnet. refer to `operator/copy.sh`. Then compile mxnet, after this, you can import `mx.sym.LSoftmax`

**Comment by Sleepychord** [comment]
thank you~
